import { StyleSheet } from 'react-native';
import { COLORS } from './colors';

export default StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: COLORS.surface },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 8, color: COLORS.text },
  back: { color: COLORS.primary, marginBottom: 12 },
  searchInput: {
    borderColor: COLORS.borderSoft,
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    backgroundColor: COLORS.surface,
    color: COLORS.text,
  },
  item: { padding: 10, borderBottomWidth: 1, borderColor: COLORS.borderSoft },
  selectedItem: { backgroundColor: '#e0f2fe' },
  itemText: { fontSize: 16, color: COLORS.text },
  section: { marginTop: 12, marginBottom: 6, fontWeight: '600', color: COLORS.text },
  empty: { textAlign: 'center', marginTop: 14, color: COLORS.textMuted },
  selectedBlock: {
    marginTop: 14,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    borderRadius: 10,
    backgroundColor: COLORS.surface,
  },
  input: {
    borderColor: COLORS.borderSoft,
    borderWidth: 1,
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
    backgroundColor: COLORS.surface,
    color: COLORS.text,
  },
  addButton: {
    backgroundColor: COLORS.success,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  addButtonText: { color: COLORS.surface, fontWeight: '700' },
  picker: { marginBottom: 8, borderWidth: 1, borderColor: COLORS.borderSoft, borderRadius: 8 },
  popupButton: { backgroundColor: COLORS.primary, paddingVertical: 10, borderRadius: 8, marginVertical: 8, alignItems: 'center' },
  popupButtonText: { color: COLORS.surface, fontWeight: '600' },
  popupOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  popupInner: {
    width: '100%',
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 16,
    shadowColor: COLORS.cardShadow,
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  popupTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12, color: COLORS.text },
  popupClose: { marginTop: 12, alignItems: 'center' },
  popupCloseText: { color: COLORS.primary, fontWeight: '600' },
  error: { color: COLORS.danger, marginTop: 8 },
});