import { StyleSheet } from 'react-native';
import { COLORS } from './colors';

export default StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: COLORS.surface },
  headerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  title: { fontSize: 24, fontWeight: '700', color: COLORS.text },
  searchInput: {
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    borderRadius: 10,
    padding: 8,
    marginBottom: 10,
    backgroundColor: COLORS.surface,
    color: COLORS.text,
  },
  item: {
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    backgroundColor: COLORS.surface,
  },
  itemLeft: { marginBottom: 8 },
  itemTitle: { fontSize: 16, fontWeight: '600', color: COLORS.text },
  itemMeta: { fontSize: 13, color: COLORS.textSecondary },
  actions: { flexDirection: 'row', gap: 12, marginTop: 8 },
  editPane: { marginTop: 8 },
  smallInput: {
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    borderRadius: 8,
    padding: 6,
    marginBottom: 6,
    backgroundColor: COLORS.surface,
    color: COLORS.text,
  },
  edit: { color: COLORS.primary, fontWeight: '500' },
  save: { color: COLORS.success, fontWeight: '500' },
  cancel: { color: COLORS.textSecondary, fontWeight: '500' },
  delete: { color: COLORS.danger, fontWeight: '500' },
  empty: { marginTop: 40, textAlign: 'center', color: COLORS.textMuted },
  error: { color: COLORS.danger, textAlign: 'center', marginTop: 40 },
  fab: {
    position: 'absolute', right: 20, bottom: 30,
    width: 56, height: 56, borderRadius: 28,
    backgroundColor: COLORS.primary,
    alignItems: 'center', justifyContent: 'center',
    shadowColor: COLORS.cardShadow, shadowOpacity: 0.2,
    shadowRadius: 6, shadowOffset: { width: 0, height: 2 },
  },
  fabText: { color: COLORS.surface, fontSize: 32, lineHeight: 32 },
});