import { StyleSheet } from 'react-native';
import { COLORS, THEME } from './colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: THEME.spacing.lg,
    backgroundColor: COLORS.surface,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: THEME.spacing.md,
  },
  backBtn: {
    padding: THEME.spacing.md,
  },
  backText: {
    fontSize: THEME.typography.fontSize.base,
    color: COLORS.primary,
    fontWeight: THEME.typography.fontWeight.medium,
  },
  title: {
    fontSize: THEME.typography.fontSize.xxxl,
    fontWeight: THEME.typography.fontWeight.bold,
    color: COLORS.text,
  },
  item: {
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    borderRadius: THEME.sizing.radius.lg,
    padding: THEME.spacing.md,
    marginBottom: THEME.spacing.md,
    backgroundColor: COLORS.surface,
  },
  empty: {
    marginTop: THEME.spacing.xxl,
    textAlign: 'center',
    color: COLORS.textMuted,
    fontSize: THEME.typography.fontSize.base,
  },
  error: {
    color: COLORS.danger,
    textAlign: 'center',
    marginTop: THEME.spacing.md,
    marginBottom: THEME.spacing.md,
    fontSize: THEME.typography.fontSize.sm,
  },
  fab: {
    position: 'absolute',
    right: THEME.spacing.xl,
    bottom: THEME.spacing.xl * 1.5,
    width: THEME.sizing.fab,
    height: THEME.sizing.fab,
    borderRadius: THEME.sizing.fabRadius,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...THEME.shadow.light,
  },
  fabText: {
    color: COLORS.buttonText,
    fontSize: THEME.typography.fontSize.huge,
    lineHeight: THEME.typography.fontSize.huge,
    fontWeight: THEME.typography.fontWeight.bold,
  },
  detailContainer: {
    flex: 1,
    padding: THEME.spacing.lg,
    backgroundColor: COLORS.surface,
  },
  detailScrollContent: {
    paddingBottom: THEME.spacing.xxl,
  },
  backButton: {
    marginBottom: THEME.spacing.lg,
  },
  sectionBlock: {
    marginBottom: THEME.spacing.lg,
  },
  recipeName: {
    fontSize: THEME.typography.fontSize.xxxxl,
    fontWeight: THEME.typography.fontWeight.bold,
    color: COLORS.text,
    marginBottom: THEME.spacing.lg,
  },
  summaryCard: {
    backgroundColor: COLORS.surfaceMuted,
    borderRadius: THEME.sizing.radius.xl,
    padding: THEME.spacing.md,
    marginBottom: THEME.spacing.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  summaryTitle: {
    fontSize: THEME.typography.fontSize.lg,
    fontWeight: THEME.typography.fontWeight.semibold,
    color: COLORS.text,
    marginBottom: THEME.spacing.sm,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.sm,
    marginTop: THEME.spacing.xs,
  },
  summaryText: {
    flex: 1,
    fontSize: THEME.typography.fontSize.sm,
    color: COLORS.textSecondary,
    lineHeight: 18,
  },
  sectionLabel: {
    fontSize: THEME.typography.fontSize.lg,
    fontWeight: THEME.typography.fontWeight.semibold,
    color: COLORS.text,
    marginTop: THEME.spacing.lg,
    marginBottom: THEME.spacing.md,
  },
  ingredientRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: THEME.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderSoft,
  },
  ingredientName: {
    fontSize: THEME.typography.fontSize.base,
    color: COLORS.text,
    flex: 1,
  },
  ingredientAmount: {
    fontSize: THEME.typography.fontSize.base,
    color: COLORS.textSecondary,
  },
  ingredientStatusCard: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: THEME.sizing.radius.lg,
    paddingVertical: THEME.spacing.sm,
    paddingHorizontal: THEME.spacing.md,
    marginBottom: THEME.spacing.sm,
    backgroundColor: COLORS.surface,
  },
  ingredientStatusTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing.sm,
  },
  ingredientTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing.sm,
    flex: 1,
  },
  ingredientTitleText: {
    flex: 1,
  },
  ingredientBadgeText: {
    fontSize: THEME.typography.fontSize.xs,
    fontWeight: THEME.typography.fontWeight.medium,
    marginTop: 2,
  },
  ingredientNeedText: {
    fontSize: THEME.typography.fontSize.sm,
    color: COLORS.textSecondary,
    lineHeight: 18,
  },
  ingredientAmountsColumn: {
    minWidth: 92,
    alignItems: 'flex-start',
  },
  pantryList: {
    marginTop: THEME.spacing.xs,
    gap: 2,
  },
  pantryItemText: {
    fontSize: THEME.typography.fontSize.xs,
    color: COLORS.textSecondary,
    lineHeight: 16,
  },
  ingredientActionButton: {
    marginTop: THEME.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.xs,
    paddingVertical: THEME.spacing.xs,
    paddingHorizontal: THEME.spacing.sm,
    borderRadius: THEME.sizing.radius.full,
    borderWidth: 1,
    borderColor: COLORS.selectedBorder,
    backgroundColor: COLORS.primarySoft,
  },
  ingredientActionButtonText: {
    fontSize: THEME.typography.fontSize.xs,
    color: COLORS.primary,
    fontWeight: THEME.typography.fontWeight.semibold,
  },
  instructions: {
    fontSize: THEME.typography.fontSize.base,
    color: COLORS.text,
    lineHeight: 20,
  },
  heroImage: {
    width: '100%',
    height: 200,
    borderRadius: THEME.sizing.radius.xl,
    marginBottom: THEME.spacing.lg,
  },
  recipeSource: {
    fontSize: THEME.typography.fontSize.sm,
    color: COLORS.textMuted,
    marginTop: -THEME.spacing.sm,
    marginBottom: THEME.spacing.md,
  },
  ingredientLine: {
    fontSize: THEME.typography.fontSize.base,
    color: COLORS.text,
    lineHeight: 22,
    paddingVertical: 2,
  },
  aiBadge: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.primarySoft,
    borderRadius: THEME.sizing.radius.full,
    paddingHorizontal: THEME.spacing.md,
    paddingVertical: THEME.spacing.xs,
    marginBottom: THEME.spacing.md,
    borderWidth: 1,
    borderColor: COLORS.selectedBorder,
  },
  aiBadgeText: {
    fontSize: THEME.typography.fontSize.xs,
    fontWeight: THEME.typography.fontWeight.semibold,
    color: COLORS.primary,
  },
  recipeActionButton: {
    marginTop: THEME.spacing.sm,
  },
});
